# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


name: 'aeroclub-scs-api'

resources:
  repositories:
  - repository: templates
    type: git
    name: BuldingTemplate

stages:
  # SonarCloud Step.

  # NOTE: We are currently releasing from a release branch so can't make trigger on master.
  - stage: Build
    condition: and(eq(variables['Build.Reason'], 'Manual'), succeeded())
    jobs:
      - template: dotnet-framework/azure-pipelines-dotnet-template-bmw.yaml@templates
